services:
  # Spring Boot API Service
  - type: web
    name: teamdev-api
    runtime: docker
    plan: free  # 無料プラン（15分でスリープ）
    region: singapore  # アジア太平洋地域
    branch: main
    autoDeploy: true  # main ブランチへの push で自動デプロイ
    dockerfilePath: ./Dockerfile
    dockerContext: .
    numInstances: 1
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_NAME
        value: TeamDevelop-API
      - key: DB_HOST
        fromDatabase:
          name: teamdev-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: teamdev-postgres
          property: port
      - key: DB_NAME
        fromDatabase:
          name: teamdev-postgres
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: teamdev-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: teamdev-postgres
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: APP_ENVIRONMENT
        value: production
      - key: APP_STARTUP_SECURITY_STRICT
        value: true
      - key: SERVER_SERVLET_SESSION_COOKIE_SAME_SITE
        value: none
      - key: SERVER_SERVLET_SESSION_COOKIE_SECURE
        value: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://portfolio-eight-ebon-25.vercel.app
      - key: SPRING_JACKSON_TIME_ZONE
        value: Asia/Tokyo
      - key: LOG_LEVEL_ROOT
        value: WARN
      - key: LOG_LEVEL_APP
        value: INFO
    buildFilter:
      paths:
        - src/**
        - build.gradle
        - gradlew
        - gradle/**
        - Dockerfile
        - render.yaml
      ignoredPaths:
        - README.md
        - docs/**
        - "*.md"

# PostgreSQL Database
databases:
  - name: teamdev-postgres
    plan: free  # 無料プラン（90日後削除、容量制限あり）
    region: singapore
    databaseName: teamdev_db
    user: teamdev_user
    ipAllowList: []
    postgresMajorVersion: "16"
