-- PostgreSQL schema definition for TeamDevelop Bravo

DROP TABLE IF EXISTS stamp_history CASCADE;
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS log_history CASCADE;
DROP TABLE IF EXISTS employee CASCADE;

CREATE TABLE employee (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_name VARCHAR(30) NOT NULL,   -- 姓（family name）
    first_name VARCHAR(30) NOT NULL,  -- 名（given name）
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    admin_flag INTEGER NOT NULL,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    schedule_start TIME WITHOUT TIME ZONE NOT NULL DEFAULT '09:00'::time,
    schedule_end TIME WITHOUT TIME ZONE NOT NULL DEFAULT '18:00'::time,
    schedule_break_minutes INTEGER NOT NULL DEFAULT 60,
    profile_metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE log_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name INTEGER,
    operation_type INTEGER,
    stamp_time TIMESTAMP WITHOUT TIME ZONE,
    employee_id INTEGER REFERENCES employee(id),
    update_employee_id INTEGER,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    detail JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE news (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_date DATE NOT NULL,
    title VARCHAR(100) NOT NULL,
    content TEXT NOT NULL CHECK (length(content) BETWEEN 1 AND 1000),
    label VARCHAR(20) NOT NULL DEFAULT 'GENERAL' CHECK (label IN ('IMPORTANT', 'SYSTEM', 'GENERAL')),
    release_flag BOOLEAN NOT NULL DEFAULT FALSE,
    update_date TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for news table
CREATE INDEX idx_news_date ON news(news_date DESC);
CREATE INDEX idx_news_release_date ON news(release_flag, news_date DESC);
CREATE INDEX idx_news_published ON news(news_date DESC) WHERE release_flag = TRUE;
CREATE INDEX idx_news_label_release ON news(label, release_flag, news_date DESC);

CREATE TABLE stamp_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year VARCHAR(4),
    month VARCHAR(2),
    day VARCHAR(2),
    employee_id INTEGER REFERENCES employee(id),
    in_time TIMESTAMP WITH TIME ZONE,
    out_time TIMESTAMP WITH TIME ZONE,
    break_start_time TIMESTAMP WITH TIME ZONE,
    break_end_time TIMESTAMP WITH TIME ZONE,
    update_employee_id INTEGER,
    update_date TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_employee_date UNIQUE (employee_id, year, month, day)
);
