-- PostgreSQL schema definition for TeamDevelop Bravo

DROP TABLE IF EXISTS stamp_history CASCADE;
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS log_history CASCADE;
DROP TABLE IF EXISTS employee CASCADE;

CREATE TABLE employee (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    admin_flag INTEGER NOT NULL,
    update_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE log_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name INTEGER,
    operation_type INTEGER,
    stamp_time TIMESTAMP WITHOUT TIME ZONE,
    employee_id INTEGER REFERENCES employee(id),
    update_employee_id INTEGER,
    update_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE news (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_date VARCHAR(10),
    content VARCHAR(255),
    release_flag INTEGER,
    update_date TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE stamp_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year VARCHAR(4),
    month VARCHAR(2),
    day VARCHAR(2),
    employee_id INTEGER REFERENCES employee(id),
    in_time TIMESTAMP WITHOUT TIME ZONE,
    out_time TIMESTAMP WITHOUT TIME ZONE,
    update_employee_id INTEGER,
    update_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uk_employee_date UNIQUE (employee_id, year, month, day)
);
