// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateEmployeeData, CreateEmployeeErrors, CreateEmployeeResponses, DeleteEmployeesData, DeleteEmployeesResponses, GetHomeOverviewData, GetHomeOverviewErrors, GetHomeOverviewResponses, GetSessionData, GetSessionResponses, GetStampHistoryData, GetStampHistoryErrors, GetStampHistoryResponses, ListEmployeesData, ListEmployeesResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, StampData, StampErrors, StampResponses, UpdateEmployeeData, UpdateEmployeeErrors, UpdateEmployeeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * ログイン
 * メールとパスワードでログインし、セッションを開始します
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => {
    return (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
        url: '/api/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * ログアウト
 * セッションを終了します
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => {
    return (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
        url: '/api/auth/logout',
        ...options
    });
};

/**
 * セッション状態取得
 * 現在の認証状態と従業員概要を返します
 */
export const getSession = <ThrowOnError extends boolean = false>(options?: Options<GetSessionData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetSessionResponses, unknown, ThrowOnError>({
        url: '/api/auth/session',
        ...options
    });
};

/**
 * 従業員削除
 * 複数IDに対応（ADMIN権限が必要）
 */
export const deleteEmployees = <ThrowOnError extends boolean = false>(options: Options<DeleteEmployeesData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteEmployeesResponses, unknown, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'SESSION',
                type: 'apiKey'
            }
        ],
        url: '/api/employees',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 従業員一覧
 * 管理者のみ絞り込み可能（adminOnly=true）
 */
export const listEmployees = <ThrowOnError extends boolean = false>(options?: Options<ListEmployeesData, ThrowOnError>) => {
    return (options?.client ?? client).get<ListEmployeesResponses, unknown, ThrowOnError>({
        url: '/api/employees',
        ...options
    });
};

/**
 * 従業員作成
 * 新規ユーザーを作成（ADMIN権限が必要）
 */
export const createEmployee = <ThrowOnError extends boolean = false>(options: Options<CreateEmployeeData, ThrowOnError>) => {
    return (options.client ?? client).post<CreateEmployeeResponses, CreateEmployeeErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'SESSION',
                type: 'apiKey'
            }
        ],
        url: '/api/employees',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 従業員更新
 * 既存ユーザーを更新（ADMIN権限が必要）
 */
export const updateEmployee = <ThrowOnError extends boolean = false>(options: Options<UpdateEmployeeData, ThrowOnError>) => {
    return (options.client ?? client).put<UpdateEmployeeResponses, UpdateEmployeeErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'SESSION',
                type: 'apiKey'
            }
        ],
        url: '/api/employees/{employeeId}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * ホーム概要
 * ログイン中の従業員情報とお知らせ一覧を返却
 */
export const getHomeOverview = <ThrowOnError extends boolean = false>(options?: Options<GetHomeOverviewData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHomeOverviewResponses, GetHomeOverviewErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'SESSION',
                type: 'apiKey'
            }
        ],
        url: '/api/home/overview',
        ...options
    });
};

/**
 * 打刻
 * 出勤/退勤の打刻を記録
 */
export const stamp = <ThrowOnError extends boolean = false>(options: Options<StampData, ThrowOnError>) => {
    return (options.client ?? client).post<StampResponses, StampErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'SESSION',
                type: 'apiKey'
            }
        ],
        url: '/api/home/stamps',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 打刻履歴取得
 * 年・月の指定がなければ当月を返却
 */
export const getStampHistory = <ThrowOnError extends boolean = false>(options?: Options<GetStampHistoryData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetStampHistoryResponses, GetStampHistoryErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'SESSION',
                type: 'apiKey'
            }
        ],
        url: '/api/stamp-history',
        ...options
    });
};
