// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | 'https://api.teamdevelop.example.com' | (string & {});
};

export type LoginRequest = {
    /**
     * メールアドレス
     */
    email: string;
    /**
     * パスワード
     */
    password: string;
};

export type LoginResponse = {
    employee: EmployeeSummaryResponse;
};

export type SessionResponse = {
    /**
     * 認証状態
     */
    authenticated: boolean;
    employee?: EmployeeSummaryResponse;
};

export type EmployeeSummaryResponse = {
    /**
     * 従業員ID
     */
    id: number;
    /**
     * 名
     */
    firstName: string;
    /**
     * 姓
     */
    lastName: string;
    /**
     * メールアドレス
     */
    email: string;
    /**
     * 管理者フラグ
     */
    admin: boolean;
};

export type EmployeeListResponse = {
    employees: Array<EmployeeSummaryResponse>;
};

export type EmployeeUpsertRequest = {
    /**
     * 名
     */
    firstName: string;
    /**
     * 姓
     */
    lastName: string;
    /**
     * メールアドレス
     */
    email: string;
    /**
     * パスワード（新規作成時必須）
     */
    password?: string | null;
    /**
     * 管理者フラグ
     */
    admin: boolean;
};

export type EmployeeDeleteRequest = {
    /**
     * 削除対象の従業員IDリスト
     */
    ids: Array<number>;
};

export type HomeDashboardResponse = {
    employee: EmployeeSummaryResponse;
    news: Array<HomeNewsItem>;
};

export type HomeNewsItem = {
    /**
     * お知らせID
     */
    id: number;
    /**
     * お知らせタイトル
     */
    title: string;
    /**
     * お知らせ内容
     */
    content: string;
    /**
     * お知らせラベル
     */
    label: 'IMPORTANT' | 'SYSTEM' | 'GENERAL';
    /**
     * お知らせ日付（YYYY-MM-DD形式）
     */
    newsDate: string;
    /**
     * 公開フラグ
     */
    releaseFlag: boolean;
};

export type NewsResponse = {
    /**
     * お知らせID
     */
    id: number;
    /**
     * お知らせ日付（YYYY-MM-DD形式）
     */
    newsDate: string;
    /**
     * お知らせタイトル
     */
    title: string;
    /**
     * お知らせ内容（最大1000文字）
     */
    content: string;
    /**
     * お知らせラベル
     */
    label: 'IMPORTANT' | 'SYSTEM' | 'GENERAL';
    /**
     * 公開フラグ（true:公開, false:非公開）
     */
    releaseFlag: boolean;
    /**
     * 更新日時（ISO 8601形式）
     */
    updateDate?: string;
};

export type NewsListResponse = {
    /**
     * お知らせリスト
     */
    news: Array<NewsResponse>;
};

export type NewsCreateRequest = {
    /**
     * お知らせ日付（YYYY-MM-DD形式）
     */
    newsDate: string;
    /**
     * お知らせタイトル（1-100文字）
     */
    title: string;
    /**
     * お知らせ内容（1-1000文字）
     */
    content: string;
    /**
     * お知らせラベル（未指定の場合はGENERALを適用）
     */
    label?: 'IMPORTANT' | 'SYSTEM' | 'GENERAL';
    /**
     * 公開フラグ（true: 公開, false: 下書き）
     */
    releaseFlag: boolean;
};

export type NewsUpdateRequest = {
    /**
     * お知らせ日付（YYYY-MM-DD形式）
     */
    newsDate: string;
    /**
     * お知らせタイトル（1-100文字）
     */
    title: string;
    /**
     * お知らせ内容（1-1000文字）
     */
    content: string;
    /**
     * お知らせラベル（未指定の場合はGENERALを適用）
     */
    label?: 'IMPORTANT' | 'SYSTEM' | 'GENERAL';
    /**
     * 公開フラグ（true: 公開, false: 下書き）
     */
    releaseFlag: boolean;
};

export type NewsPublishRequest = {
    /**
     * 公開フラグ（true: 公開, false: 非公開）
     */
    releaseFlag: boolean;
};

export type ProfileStatisticsResponse = {
    summary: AttendanceSummaryResponse;
    /**
     * 過去6か月分の月次勤怠データ
     */
    monthly: Array<MonthlyAttendanceResponse>;
};

export type AttendanceSummaryResponse = {
    currentMonth: AttendanceSummaryCurrentMonth;
    /**
     * 直近6か月の勤怠トレンド
     */
    trendData: Array<AttendanceSummaryTrendItem>;
};

export type AttendanceSummaryCurrentMonth = {
    /**
     * 月間総労働時間（時間）
     */
    totalHours: number;
    /**
     * 月間残業時間（時間）
     */
    overtimeHours: number;
    /**
     * 月間の遅刻回数
     */
    lateCount: number;
    /**
     * 有給消化時間（時間）
     */
    paidLeaveHours: number;
};

export type AttendanceSummaryTrendItem = {
    /**
     * 月（YYYY-MM形式）
     */
    month: string;
    /**
     * 月間総労働時間（時間）
     */
    totalHours: number;
    /**
     * 月間残業時間（時間）
     */
    overtimeHours: number;
};

export type MonthlyAttendanceResponse = {
    /**
     * 月（YYYY-MM形式）
     */
    month: string;
    /**
     * 月間総労働時間（時間）
     */
    totalHours: number;
    /**
     * 月間残業時間（時間）
     */
    overtimeHours: number;
    /**
     * 遅刻回数
     */
    lateCount: number;
    /**
     * 有給消化時間（時間）
     */
    paidLeaveHours: number;
};

export type StampRequest = {
    /**
     * 打刻時刻（ISO形式）
     */
    stampTime: string;
    /**
     * 打刻種別（1:出勤、2:退勤）
     */
    stampType: '1' | '2';
    /**
     * 夜勤フラグ（0:通常、1:夜勤）
     */
    nightWorkFlag: '0' | '1';
};

export type StampResponse = {
    /**
     * 打刻結果メッセージ
     */
    message: string;
};

export type StampUpdateRequest = unknown & {
    /**
     * 更新後の出勤時刻（HH:mm）
     */
    inTime?: string;
    /**
     * 更新後の退勤時刻（HH:mm）
     */
    outTime?: string;
};

export type StampHistoryResponse = {
    /**
     * 対象年
     */
    selectedYear: string;
    /**
     * 対象月
     */
    selectedMonth: string;
    /**
     * 選択可能な年リスト
     */
    years: Array<string>;
    /**
     * 選択可能な月リスト
     */
    months: Array<string>;
    entries: Array<StampHistoryEntryResponse>;
};

export type StampHistoryEntryResponse = {
    /**
     * 打刻履歴ID
     */
    id?: number | null;
    /**
     * 年
     */
    year?: string | null;
    /**
     * 月
     */
    month?: string | null;
    /**
     * 日
     */
    day?: string | null;
    /**
     * 曜日
     */
    dayOfWeek?: string | null;
    /**
     * 従業員ID
     */
    employeeId?: number | null;
    /**
     * 従業員名
     */
    employeeName?: string | null;
    /**
     * 更新者名
     */
    updateEmployeeName?: string | null;
    /**
     * 出勤時刻
     */
    inTime?: string | null;
    /**
     * 退勤時刻
     */
    outTime?: string | null;
    /**
     * 更新日時
     */
    updateDate?: string | null;
};

export type ErrorResponse = {
    /**
     * エラーメッセージ
     */
    message: string;
    /**
     * エラー詳細情報
     */
    details?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * 認証失敗
     */
    401: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * ログイン成功
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * ログアウト成功
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/session';
};

export type GetSessionResponses = {
    /**
     * セッション情報
     */
    200: SessionResponse;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type DeleteEmployeesData = {
    body: EmployeeDeleteRequest;
    path?: never;
    query?: never;
    url: '/api/employees';
};

export type DeleteEmployeesResponses = {
    /**
     * 削除成功
     */
    204: void;
};

export type DeleteEmployeesResponse = DeleteEmployeesResponses[keyof DeleteEmployeesResponses];

export type ListEmployeesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 管理者のみ表示
         */
        adminOnly?: boolean;
    };
    url: '/api/employees';
};

export type ListEmployeesResponses = {
    /**
     * 従業員一覧
     */
    200: EmployeeListResponse;
};

export type ListEmployeesResponse = ListEmployeesResponses[keyof ListEmployeesResponses];

export type CreateEmployeeData = {
    body: EmployeeUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/employees';
};

export type CreateEmployeeErrors = {
    /**
     * リクエストエラー
     */
    400: ErrorResponse;
    /**
     * メールアドレス重複
     */
    409: ErrorResponse;
};

export type CreateEmployeeError = CreateEmployeeErrors[keyof CreateEmployeeErrors];

export type CreateEmployeeResponses = {
    /**
     * 作成成功
     */
    201: EmployeeSummaryResponse;
};

export type CreateEmployeeResponse = CreateEmployeeResponses[keyof CreateEmployeeResponses];

export type UpdateEmployeeData = {
    body: EmployeeUpsertRequest;
    path: {
        employeeId: number;
    };
    query?: never;
    url: '/api/employees/{employeeId}';
};

export type UpdateEmployeeErrors = {
    /**
     * 従業員が見つかりません
     */
    404: ErrorResponse;
    /**
     * メールアドレス重複
     */
    409: ErrorResponse;
};

export type UpdateEmployeeError = UpdateEmployeeErrors[keyof UpdateEmployeeErrors];

export type UpdateEmployeeResponses = {
    /**
     * 更新成功
     */
    200: EmployeeSummaryResponse;
};

export type UpdateEmployeeResponse = UpdateEmployeeResponses[keyof UpdateEmployeeResponses];

export type GetHomeOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/home/overview';
};

export type GetHomeOverviewErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
};

export type GetHomeOverviewError = GetHomeOverviewErrors[keyof GetHomeOverviewErrors];

export type GetHomeOverviewResponses = {
    /**
     * ホーム画面情報
     */
    200: HomeDashboardResponse;
};

export type GetHomeOverviewResponse = GetHomeOverviewResponses[keyof GetHomeOverviewResponses];

export type StampData = {
    body: StampRequest;
    path?: never;
    query?: never;
    url: '/api/home/stamps';
};

export type StampErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
};

export type StampError = StampErrors[keyof StampErrors];

export type StampResponses = {
    /**
     * 打刻成功
     */
    200: StampResponse;
};

export type StampResponse2 = StampResponses[keyof StampResponses];

export type GetStampHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 年（YYYY形式）
         */
        year?: string;
        /**
         * 月（MM形式）
         */
        month?: string;
    };
    url: '/api/stamp-history';
};

export type GetStampHistoryErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
};

export type GetStampHistoryError = GetStampHistoryErrors[keyof GetStampHistoryErrors];

export type GetStampHistoryResponses = {
    /**
     * 打刻履歴
     */
    200: StampHistoryResponse;
};

export type GetStampHistoryResponse = GetStampHistoryResponses[keyof GetStampHistoryResponses];

export type DeleteStampData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stamps/{id}';
};

export type DeleteStampErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
    /**
     * 権限がありません
     */
    403: ErrorResponse;
    /**
     * 対象の打刻が見つかりません
     */
    404: ErrorResponse;
};

export type DeleteStampError = DeleteStampErrors[keyof DeleteStampErrors];

export type DeleteStampResponses = {
    /**
     * 削除成功
     */
    204: void;
};

export type DeleteStampResponse = DeleteStampResponses[keyof DeleteStampResponses];

export type UpdateStampData = {
    body: StampUpdateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/stamps/{id}';
};

export type UpdateStampErrors = {
    /**
     * 入力値が不正です
     */
    400: ErrorResponse;
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
    /**
     * 権限がありません
     */
    403: ErrorResponse;
    /**
     * 対象の打刻が見つかりません
     */
    404: ErrorResponse;
};

export type UpdateStampError = UpdateStampErrors[keyof UpdateStampErrors];

export type UpdateStampResponses = {
    /**
     * 更新成功
     */
    204: void;
};

export type UpdateStampResponse = UpdateStampResponses[keyof UpdateStampResponses];

export type GetAllNewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/news';
};

export type GetAllNewsErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
};

export type GetAllNewsError = GetAllNewsErrors[keyof GetAllNewsErrors];

export type GetAllNewsResponses = {
    /**
     * お知らせ一覧
     */
    200: NewsListResponse;
};

export type GetAllNewsResponse = GetAllNewsResponses[keyof GetAllNewsResponses];

export type CreateNewsData = {
    body: NewsCreateRequest;
    path?: never;
    query?: never;
    url: '/api/news';
};

export type CreateNewsErrors = {
    /**
     * バリデーションエラー
     */
    400: ErrorResponse;
    /**
     * 権限がありません
     */
    403: ErrorResponse;
};

export type CreateNewsError = CreateNewsErrors[keyof CreateNewsErrors];

export type CreateNewsResponses = {
    /**
     * 作成成功
     */
    201: NewsResponse;
};

export type CreateNewsResponse = CreateNewsResponses[keyof CreateNewsResponses];

export type GetPublishedNewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/news/published';
};

export type GetPublishedNewsResponses = {
    /**
     * 公開お知らせ一覧
     */
    200: NewsListResponse;
};

export type GetPublishedNewsResponse = GetPublishedNewsResponses[keyof GetPublishedNewsResponses];

export type DeleteNewsData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/news/{id}';
};

export type DeleteNewsErrors = {
    /**
     * 権限がありません
     */
    403: ErrorResponse;
    /**
     * お知らせが見つかりません
     */
    404: ErrorResponse;
};

export type DeleteNewsError = DeleteNewsErrors[keyof DeleteNewsErrors];

export type DeleteNewsResponses = {
    /**
     * 削除成功
     */
    204: void;
};

export type DeleteNewsResponse = DeleteNewsResponses[keyof DeleteNewsResponses];

export type UpdateNewsData = {
    body: NewsUpdateRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/news/{id}';
};

export type UpdateNewsErrors = {
    /**
     * バリデーションエラー
     */
    400: ErrorResponse;
    /**
     * 権限がありません
     */
    403: ErrorResponse;
    /**
     * お知らせが見つかりません
     */
    404: ErrorResponse;
};

export type UpdateNewsError = UpdateNewsErrors[keyof UpdateNewsErrors];

export type UpdateNewsResponses = {
    /**
     * 更新成功
     */
    200: NewsResponse;
};

export type UpdateNewsResponse = UpdateNewsResponses[keyof UpdateNewsResponses];

export type ToggleNewsPublishData = {
    body: NewsPublishRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/news/{id}/publish';
};

export type ToggleNewsPublishErrors = {
    /**
     * バリデーションエラー
     */
    400: ErrorResponse;
    /**
     * 権限がありません
     */
    403: ErrorResponse;
    /**
     * お知らせが見つかりません
     */
    404: ErrorResponse;
};

export type ToggleNewsPublishError = ToggleNewsPublishErrors[keyof ToggleNewsPublishErrors];

export type ToggleNewsPublishResponses = {
    /**
     * 設定成功
     */
    204: void;
};

export type ToggleNewsPublishResponse = ToggleNewsPublishResponses[keyof ToggleNewsPublishResponses];

export type GetSelfProfileStatisticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/profile/me/statistics';
};

export type GetSelfProfileStatisticsErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
};

export type GetSelfProfileStatisticsError = GetSelfProfileStatisticsErrors[keyof GetSelfProfileStatisticsErrors];

export type GetSelfProfileStatisticsResponses = {
    /**
     * 勤怠統計取得成功
     */
    200: ProfileStatisticsResponse;
};

export type GetSelfProfileStatisticsResponse = GetSelfProfileStatisticsResponses[keyof GetSelfProfileStatisticsResponses];
