// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | 'https://api.teamdevelop.example.com' | (string & {});
};

export type LoginRequest = {
    /**
     * メールアドレス
     */
    email: string;
    /**
     * パスワード
     */
    password: string;
};

export type LoginResponse = {
    employee: EmployeeSummaryResponse;
};

export type SessionResponse = {
    /**
     * 認証状態
     */
    authenticated: boolean;
    employee?: EmployeeSummaryResponse;
};

export type EmployeeSummaryResponse = {
    /**
     * 従業員ID
     */
    id: number;
    /**
     * 名
     */
    firstName: string;
    /**
     * 姓
     */
    lastName: string;
    /**
     * メールアドレス
     */
    email: string;
    /**
     * 管理者フラグ
     */
    admin: boolean;
};

export type EmployeeListResponse = {
    employees: Array<EmployeeSummaryResponse>;
};

export type EmployeeUpsertRequest = {
    /**
     * 名
     */
    firstName: string;
    /**
     * 姓
     */
    lastName: string;
    /**
     * メールアドレス
     */
    email: string;
    /**
     * パスワード（新規作成時必須）
     */
    password?: string | null;
    /**
     * 管理者フラグ
     */
    admin: boolean;
};

export type EmployeeDeleteRequest = {
    /**
     * 削除対象の従業員IDリスト
     */
    ids: Array<number>;
};

export type HomeDashboardResponse = {
    employee: EmployeeSummaryResponse;
    news: Array<HomeNewsItem>;
};

export type HomeNewsItem = {
    /**
     * お知らせID
     */
    id: number;
    /**
     * お知らせ内容
     */
    content: string;
    /**
     * お知らせ日付
     */
    newsDate: string;
    /**
     * 公開フラグ
     */
    releaseFlag: boolean;
};

export type StampRequest = {
    /**
     * 打刻時刻（ISO形式）
     */
    stampTime: string;
    /**
     * 打刻種別（1:出勤、2:退勤）
     */
    stampType: '1' | '2';
    /**
     * 夜勤フラグ（0:通常、1:夜勤）
     */
    nightWorkFlag: '0' | '1';
};

export type StampResponse = {
    /**
     * 打刻結果メッセージ
     */
    message: string;
};

export type StampHistoryResponse = {
    /**
     * 対象年
     */
    year: string;
    /**
     * 対象月
     */
    month: string;
    /**
     * 選択可能な年リスト
     */
    years: Array<string>;
    /**
     * 選択可能な月リスト
     */
    months: Array<string>;
    entries: Array<StampHistoryEntryResponse>;
};

export type StampHistoryEntryResponse = {
    /**
     * 打刻履歴ID
     */
    id?: number | null;
    /**
     * 年
     */
    year?: string | null;
    /**
     * 月
     */
    month?: string | null;
    /**
     * 日
     */
    day?: string | null;
    /**
     * 曜日
     */
    dayOfWeek?: string | null;
    /**
     * 従業員ID
     */
    employeeId?: number | null;
    /**
     * 従業員名
     */
    employeeName?: string | null;
    /**
     * 更新者名
     */
    updateEmployeeName?: string | null;
    /**
     * 出勤時刻
     */
    inTime?: string | null;
    /**
     * 退勤時刻
     */
    outTime?: string | null;
    /**
     * 更新日時
     */
    updateDate?: string | null;
};

export type ErrorResponse = {
    /**
     * エラーメッセージ
     */
    message: string;
    /**
     * エラー詳細情報
     */
    details?: {
        [key: string]: unknown;
    };
};

export type LoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * 認証失敗
     */
    401: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * ログイン成功
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutResponses = {
    /**
     * ログアウト成功
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/session';
};

export type GetSessionResponses = {
    /**
     * セッション情報
     */
    200: SessionResponse;
};

export type GetSessionResponse = GetSessionResponses[keyof GetSessionResponses];

export type DeleteEmployeesData = {
    body: EmployeeDeleteRequest;
    path?: never;
    query?: never;
    url: '/api/employees';
};

export type DeleteEmployeesResponses = {
    /**
     * 削除成功
     */
    204: void;
};

export type DeleteEmployeesResponse = DeleteEmployeesResponses[keyof DeleteEmployeesResponses];

export type ListEmployeesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 管理者のみ表示
         */
        adminOnly?: boolean;
    };
    url: '/api/employees';
};

export type ListEmployeesResponses = {
    /**
     * 従業員一覧
     */
    200: EmployeeListResponse;
};

export type ListEmployeesResponse = ListEmployeesResponses[keyof ListEmployeesResponses];

export type CreateEmployeeData = {
    body: EmployeeUpsertRequest;
    path?: never;
    query?: never;
    url: '/api/employees';
};

export type CreateEmployeeErrors = {
    /**
     * リクエストエラー
     */
    400: ErrorResponse;
    /**
     * メールアドレス重複
     */
    409: ErrorResponse;
};

export type CreateEmployeeError = CreateEmployeeErrors[keyof CreateEmployeeErrors];

export type CreateEmployeeResponses = {
    /**
     * 作成成功
     */
    201: EmployeeSummaryResponse;
};

export type CreateEmployeeResponse = CreateEmployeeResponses[keyof CreateEmployeeResponses];

export type UpdateEmployeeData = {
    body: EmployeeUpsertRequest;
    path: {
        employeeId: number;
    };
    query?: never;
    url: '/api/employees/{employeeId}';
};

export type UpdateEmployeeErrors = {
    /**
     * 従業員が見つかりません
     */
    404: ErrorResponse;
    /**
     * メールアドレス重複
     */
    409: ErrorResponse;
};

export type UpdateEmployeeError = UpdateEmployeeErrors[keyof UpdateEmployeeErrors];

export type UpdateEmployeeResponses = {
    /**
     * 更新成功
     */
    200: EmployeeSummaryResponse;
};

export type UpdateEmployeeResponse = UpdateEmployeeResponses[keyof UpdateEmployeeResponses];

export type GetHomeOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/home/overview';
};

export type GetHomeOverviewErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
};

export type GetHomeOverviewError = GetHomeOverviewErrors[keyof GetHomeOverviewErrors];

export type GetHomeOverviewResponses = {
    /**
     * ホーム画面情報
     */
    200: HomeDashboardResponse;
};

export type GetHomeOverviewResponse = GetHomeOverviewResponses[keyof GetHomeOverviewResponses];

export type StampData = {
    body: StampRequest;
    path?: never;
    query?: never;
    url: '/api/home/stamps';
};

export type StampErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
};

export type StampError = StampErrors[keyof StampErrors];

export type StampResponses = {
    /**
     * 打刻成功
     */
    200: StampResponse;
};

export type StampResponse2 = StampResponses[keyof StampResponses];

export type GetStampHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 年（YYYY形式）
         */
        year?: string;
        /**
         * 月（MM形式）
         */
        month?: string;
    };
    url: '/api/stamp-history';
};

export type GetStampHistoryErrors = {
    /**
     * 認証が必要です
     */
    401: ErrorResponse;
};

export type GetStampHistoryError = GetStampHistoryErrors[keyof GetStampHistoryErrors];

export type GetStampHistoryResponses = {
    /**
     * 打刻履歴
     */
    200: StampHistoryResponse;
};

export type GetStampHistoryResponse = GetStampHistoryResponses[keyof GetStampHistoryResponses];
