name: AI Auto-Fix Done
on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

permissions:
  pull-requests: write
  issues: write

jobs:
  finalize:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const prs = await github.request(run.pull_requests_url);
            if (!prs.data.length) return;
            const pr = prs.data[0];

            const { owner, repo } = context.repo;
            const rc = await github.rest.pulls.listReviewComments({ owner, repo, pull_number: pr.number, per_page: 100 });
            const ic = await github.rest.issues.listComments({ owner, repo, issue_number: pr.number, per_page: 100 });
            
            const isHighOrCritical = (c) => /\b(high|critical)\b/i.test(c.body || "");
            const hasResolvedFlag = (c) => /\b(resolved|fixed)\b/i.test(c.body || "") || /✅/.test(c.body || "");
            const unresolved = (c) => isHighOrCritical(c) && !hasResolvedFlag(c);
            const remaining = [...rc.data, ...ic.data].filter(unresolved);

            if (remaining.length === 0) {
            try {
              await github.rest.issues.createComment({
                owner, repo, issue_number: pr.number,
                body: "✅ CI passed & all High/Critical findings are resolved. Auto-fix complete."
              });
            } catch (e) {
              if (e.status === 404) {
                await github.rest.issues.createLabel({
                  owner, repo, name: "auto-fix:done", color: "0e8a16",
                  description: "All High/Critical findings resolved"
                }).catch(() => {});
                await github.rest.issues.addLabels({
                  owner, repo, issue_number: pr.number, labels: ["auto-fix:done"]
                });
              } else {
                throw e;
              }
            }
            }
